Test Screens UI Completed
BC-NOV-20-Proyectos/alerta-covid-mobile-nov20-rn-team-02 pull request #15
Opened 2021-03-26 16:44 UTC by vmagana3

Co-authored-by: Mariam Rivera <riverahmariam@gmail.com>
Co-authored-by: Juan Carbajal <jjcr0397@gmail.com>

# Description
We have implemented UI type test screens,  to choose type test

  
  ## Screenshots 
![image](https://user-images.githubusercontent.com/47892616/112665012-36895680-8e20-11eb-8665-255b7e358f04.png)
![image](https://user-images.githubusercontent.com/47892616/112665070-46a13600-8e20-11eb-86be-b604ab3a1163.png)

2021-03-26 16:55 UTC, fernandoamz requested changes

2021-03-26 16:55 UTC, fernandoamz commented on COVID19/src/screens/Login.js
>        //Aquí colocar antes de enviar los datos del formulario
Remove unnecessary comments

2021-03-26 16:55 UTC, fernandoamz commented on COVID19/src/screens/TestDetails.js
> +//import DateTimePicker from '@react-native-community/datetimepicker';
Remove this unnecessary import

2021-03-26 18:56 UTC, oswaldotovar32 submitted a review, later dismissed

2021-03-30 17:32 UTC, LeyaimMagma requested changes

2021-03-30 17:32 UTC, LeyaimMagma commented on COVID19/src/screens/TestDetails.js
> +        // fadeToColor={{background: 'red'}}
Remove this line

2021-03-30 17:32 UTC, LeyaimMagma commented on COVID19/src/screens/TestDetails.js
> +        textColor="#5A4DCC"
Move this color to constants

2021-03-30 17:32 UTC, LeyaimMagma commented on COVID19/src/screens/Login.js
> +          onChangeInput={(e) => onChange(e, 'usuario')}
Add usuario to constants file

2021-03-30 17:32 UTC, LeyaimMagma commented on COVID19/src/screens/Login.js
> +          onChangeInput={(e) => onChange(e, 'contrasenia')}
Add contraseña to constant file

2021-03-30 18:13 UTC, hearagmu commented on COVID19/src/screens/TestDetails.js
> +        // fadeToColor={{background: 'red'}}
Fixed

2021-03-30 18:13 UTC, hearagmu commented on COVID19/src/screens/Login.js
> +          onChangeInput={(e) => onChange(e, 'contrasenia')}
Fixed

2021-03-30 18:17 UTC, LeyaimMagma approved these changes

2021-03-30 18:57 UTC, jjcr11 approved these changes

2021-03-30 19:23 UTC, mariam-rivera approved these changes

2021-04-08 12:39 UTC, fernandoamz approved these changes

2021-04-08 15:21 UTC, merged